### PR TITLE
Migrate to github actions

### LINKED ISSUE #295: Move CICD over to GitHub actions and GitHub container repo

### PR DESCRIPTION
**Pull request by jonseitz**
This PR patches in the GitHub Actions workflows from [my testing repository](https://github.com/jonseitz/actions-test) to replace the Travis-ci configurations, now that Travis's billing changes have stopped all of our builds. I've pulled over the commit history from that repo, since the commit comments and iterative development of the workflows could be relevant for future projects. As brief recap, the series of workflows here will:

1. Run all of our static analysis: lints, tests, coverage on every push and pull request
2. Check that you're not trying to merge a feature branch into `main`
3. Automatically increment the package version per our [Release Management guidelines](https://github.com/seas-computing/dev-team-notes/blob/main/release_management.md)
4. Publish `qa`, `stable`, and version-tagged docker images to GitHub container repository
5. Deploy our documentation to `gh-pages`

Beyond the changes I demonstrated on 1/22, this adds the "02-pr-check" stage that verifies that only `develop` can be merged into our `main` branch. 

For testing, I can provide access to [my testing repository](https://github.com/jonseitz/actions-test) so you can run through the push/PR/merge process and see which flows run when.

Note: Even after this is merged into `develop`, the Docker and Documentation workflows won't run until they exist in the main branch (i.e., when #293 is merged).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to change)

## Checklist:

- [x] I have run `eslint` on the code
- [ ] I have added JSDoc for all of my code (where applicable)
- [ ] I have added tests to cover my changes.

## Priority:
- [x] Normal 
- [ ] High 

## Related Issues:

Fixes #295

### CODE REVIEW

**Review by natalynyu — COMMENTED** [review]
@jonseitz I was doing some fiddling around in the `actions-test` repo and was able to do a [push to `main` from my feature branch,](https://github.com/jonseitz/actions-test/pull/58) `feature/new-test2`:
image
When I pushed up my code to Github from the feature branch, the build temporarily says that all checks have passed and allows me to click merge before it then runs all the tests, fails, and then doesn't allow me to merge to `main`. I suppose it is unlikely for someone to click merge within those few seconds before the build loads again, but is there any way to prevent it from saying all checks have passed when it first receives the pushed code?
image

**Comment by jonseitz** [comment]
Ah, that's a really good point and it's something that I hadn't really gotten around to addressing. By default, there's actually nothing preventing you from merging a PR that fails some of the status checks -- you don't even have to be fast to do it. The button won't be green, but you can still click it and merge it just fine.

What we can do though, is set up branch protection rules in the repo settings to ensure that 1.) every PR gets reviewed and 2.) every PR must pass all status checks. I did that and created [a new, invalid PR](https://github.com/jonseitz/actions-test/pull/60) so you can see. 

Those rules will need to set for each repo, but we might be able to do that in our boilerplate repo and carry it into any new projects.

**Comment by natalynyu** [comment]
@jonseitz Oh ok, cool - thanks for clarifying. Everything looks good - I approve!

**Review by natalynyu — APPROVED** [review]
Approved!

**Pull request merged**
